### ISSUE TITLE
Developing Authentificationan & Authorization

### ISSUE THREAD

**Issue by pavelbidenko2018** [pavelbidenko2018/spring-auth#1]
## Task:
Develop Authentificationan & Authorization backend and frontend

### Steps
- [x] add spring-boot-jpa db support
- [ ] link spring boot auth classes with mySql to store users in db 
- [ ] develop login, logout and default views
- [ ] add oAuth2
